name: viaja_segura_movil
description: "viaja_segura_movil"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.1
  flutter_sticky_header: ^0.7.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.1.1
  location: ^7.0.1
  geolocator_android: 4.6.1
  http: ^1.3.0
  flutter_polyline_points: ^2.1.0
  permission_handler: ^11.4.0
  qr_code_scanner_plus: ^2.0.10+1
  url_launcher: ^6.3.1
  timeline_tile: ^2.0.0
  flutter_rating: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
